### ISSUE TITLE
Improve the cart page

### ISSUE THREAD

**Issue by Sneha123-zudo** [Anushkabh/krishiconnect#13]
I want to improve the cart page of the website , please assign me this issue under GSSOC'24.

**Comment by Anushkabh** [comment]
@Sneha123-zudo go ahead and complete it

**Comment by sakshiiiii26** [comment]
Hello!! @Anushkabh  I am a contributor of GSSoC 24 and I would like to design this page in attractive way. So I request you to please assign me this task thankyou!!

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
