### ISSUE TITLE
[Fix]: Changing the font color over the dark background to make it readable easily. 

### ISSUE THREAD

**Issue by souvik-maity** [Anushkabh/krishiconnect#17]
![IMG_20240510_113914.jpg](https://github.com/Anushkabh/krishiconnect/assets/145227417/6d3c67d1-12ff-46ce-84ec-65d1c7ad532e)

The white font color is not clearly readable over the vibrant background.Changing  the font-color and size may help.
Eagerly waiting to contribute .Kindly assign this to me .

**Comment by dhanushsurendra** [comment]
Hey @Anushkabh , I think adding an overlay might make the font visible. Assign this issue to me. I'll fix it

**Comment by Akshatakapare** [comment]
I would like to contribute to this issue. Could you please consider assigning this issue to me? I'm committed to dedicating my time and effort to delivering a high-quality design that aligns with the project's goals.

Looking forward to the opportunity to work on this exciting project!

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
