### ISSUE TITLE
Adding realtime news flashes.

### ISSUE THREAD

**Issue by KhushiTiwarii** [Anushkabh/krishiconnect#19]
![image](https://github.com/Anushkabh/krishiconnect/assets/137861160/8f8a73a8-c70c-459e-83ff-ed7cca40f5ad)

The news will keep on updating upon using news api

**Comment by KhushiTiwarii** [comment]
Please assign me this under gssoc

**Comment by Anushkabh** [comment]
@KhushiTiwarii first complete the previous issue.
raise one issue at a time

**Comment by KhushiTiwarii** [comment]
ohk

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
