### ISSUE TITLE
Updating UI/UX design of login form

### ISSUE THREAD

**Issue by PiyushKalyanpy** [Anushkabh/krishiconnect#22]
Login page : https://anushkabh.github.io/krishiconnect/login.html

I am a UI UX designer and Frontend developer. I can make the login page more engaging in terms of Visual design and user experience.
I have worked on many projects before where I improved the design of the websites, so I think that I can do it well.

Please assign me this issue under GSSoc24 (Level3)

**Comment by Anushkabh** [comment]
@PiyushKalyanpy go ahead

**Comment by dhanushsurendra** [comment]
Hey @Anushkabh, I can design a better login form. Please assign this issue to me under gssoc

**Comment by Vaibhavsg17** [comment]
@Anushkabh issue is still pending, assign me this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
