### ISSUE TITLE
Alert after adding any product in the cart

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#23]
When we add any product in the cart, it does not show any message

**Comment by anurag2787** [comment]
Hey @Anushkabh , kindly assign me this issue.

**Comment by sakshiiiii26** [comment]
Hello!! @anuza08  I am a contributor of GSSoC 24 and I would like to add this feature . So I request you to please assign me this task thankyou!!

**Comment by aakrati14** [comment]
Please assign this issue to me. I can fix this issue. @Anushkabh

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
