### ISSUE TITLE
Not allowing to check out if the cart is empty

### ISSUE THREAD

**Issue by anuza08** [Anushkabh/krishiconnect#25]
Giving an alert that 'cart is empty ' before checking out

**Comment by VedaVarxha** [comment]
@Anushkabh I would like to work on this issue under GSSOC'24. Please assign it to me

**Comment by Anushkabh** [comment]
@anuza08 kindly raise and complete one issue at a time

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
