### ISSUE TITLE
Converting current website to NextJS

### ISSUE THREAD

**Issue by yujit2003** [Anushkabh/krishiconnect#31]
Next. js shines in frontend development with its optimized rendering techniques and easy-to-use features.

I want to work in this issue please assign this to me

**Comment by Anushkabh** [comment]
@yujit2003 kindly explain your approach first

**Comment by yujit2003** [comment]
@Anushkabh currently website is in html/css, we can convert all frontend pages into nextJS 
where all pages will be present and images shall be stored in one folder so our project will be more optimised and easy to understand, with many other functionalities like SEOs, dynamic routing, etc

**Comment by Anushkabh** [comment]
okay go ahead @yujit2003

**Comment by Anushkabh** [comment]
@yujit2003  are you working?

**Comment by yujit2003** [comment]
Yes @Anushkabh

**Comment by Rohitha-pudu** [comment]
Is it still open @Anushkabh ,I want to work on this ,if possible please assign this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
