### ISSUE TITLE
Interactivity Inhencement & Hover Over BUY, Harvest, Delivery ICON

### ISSUE THREAD

**Issue by sahajoydeep** [Anushkabh/krishiconnect#38]
hi @Anushkabh I submit to a hover effect over the BUY, HARVEST, DELIVERY ICON,

When the user hovers over them, the blank part on the icon gets filled and the filled part (before) gets blank, it will give a really soothing experience to the users, and it will make the landing page more interactive.

I can work on this and make this happen using CSS or Figma, Please assign me this task.

<img width="1440" alt="Screenshot 2024-05-11 at 1 35 13 AM" src="https://github.com/Anushkabh/krishiconnect/assets/88198830/f55c22d4-a5b2-45d6-8f19-dfe09b763446">

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!

**Comment by sahajoydeep** [comment]
Hi @himanshu-03 I guess the issue is no longer needed, and finding difficulties finding new issues and getting one.

I really want to contribute, if you have anything related to front end please suggest, I'll really appreciate if I can contribute more to the project.
