### ISSUE TITLE
BUG: Navbar not working in other pages.

### ISSUE THREAD

**Issue by nagalakshmi08** [Anushkabh/krishiconnect#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Navbar is not working in other pages except the home page.

https://github.com/Anushkabh/krishiconnect/assets/121669832/d2d3a8e1-de3c-49c6-8684-f80566391d66

Please assign me this issue, I would like to contribute to this project under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!

**Comment by nagalakshmi08** [comment]
> Hi there!
> 
> Thank you for opening this issue! 😊
> 
> I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!
> 
> Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.
> 
> Happy coding!

Hi, I have cloned the repository and ran the code, the I found that the issue was resolved. I think someone solved this in some another PR. Now the navbar is working in all pages.
