### ISSUE TITLE
[Feature] Adding a side bar to the homepage

### ISSUE THREAD

**Issue by TanyaSingh103** [Anushkabh/krishiconnect#48]
Adding a sidebar to the home page will enable easier navigation for the user. Kindly assign this to me under the label gssoc 24 so that I can work on this.

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
