### ISSUE TITLE
Enhancement of some buttons

### ISSUE THREAD

**Issue by madhurima316** [Anushkabh/krishiconnect#49]
I want to add hover effects to the CONFIRM ORDER button and the buttons of MY CART section.

**Comment by madhurima316** [comment]
Please assign me this issue under GSSoC24

**Comment by Anushkabh** [comment]
@madhurima316 explain using ss

**Comment by madhurima316** [comment]
I would like to add hover effects for these buttons - Confirm Order button and the 3 buttons of My Cart section.
![Screenshot 2024-05-12 220446](https://github.com/Anushkabh/krishiconnect/assets/145414858/ddf6397f-319a-4c73-a76d-007a6ada6237)
![Screenshot 2024-05-12 220405](https://github.com/Anushkabh/krishiconnect/assets/145414858/ef51a788-5543-460e-87ce-365c5edde151)

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
