### ISSUE TITLE
Feat: Adding the github repo link to the footer github icon 

### ISSUE THREAD

**Issue by Amruta7203** [Anushkabh/krishiconnect#605]
### Describe the feature

The current github icon does not have any on click function. It should be linked to this github repo of krishiconnect.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/116087736/5cb6e115-ee2d-44fe-92c1-3292a6bf7557)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by anshikatiwari20** [comment]
**Description:**
Currently, the GitHub icon in the footer does not link to the project's GitHub repository. I would like to add the repository link to the icon so that users can easily navigate to the GitHub repo by clicking the icon. This will improve accessibility and encourage more user engagement with the project's codebase.

**Screenshot:**
![Screenshot 2024-06-18 185838](https://github.com/Anushkabh/krishiconnect/assets/143124119/b9db6678-6dec-4568-9d21-8e6fc3c1fc60)

I am a GSSoC contributor and would like to work on adding the GitHub repo link to the footer GitHub icon as described in issue #605. Could you please assign this issue to me? Thank you!

**Comment by himanshu-03** [comment]
Hello @Amruta7203!

please fix the asssigned issues first and let me know when u are done with them first.

**Comment by himanshu-03** [comment]
hey @Amruta7203 !

We have updated the footer and rn we dont have any github links in it.
