### ISSUE TITLE
Overlapping Navigation Menu Items in Mobile App

### ISSUE THREAD

**Issue by nandu-99** [Anushkabh/krishiconnect#7]
<img width="411" alt="Screenshot 2024-05-09 at 11 47 45 AM" src="https://github.com/Anushkabh/krishiconnect/assets/145771776/a1eb6e19-1d13-4831-9bcf-e68079679af0">

Navigation menu items overlap on mobile app, causing usability issues. Recommend implementing responsive design for better user experience.Please assign this issue to me, i would love to resolve this issue

**Comment by nandu-99** [comment]
Thank you so much

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
