### ISSUE TITLE
FAQ Section Sequencing Issue

### ISSUE THREAD

**Issue by nandu-99** [Anushkabh/krishiconnect#8]
The FAQ section on our open-source organization's website displays questions in a disordered sequence (e.g., 1, 3, 4, 5, 6,12,14,15,16,19,22,24). This disrupts user experience and requires reorganization for clarity. please assign this issue to me, i would love to resolve this issue
![Uploading Screenshot 2024-05-09 at 11.55.12 AM.png…]()

**Comment by MehekFatima** [comment]
Hi @nandu-99 and @Anushkabh  ,

I hope this message finds you well. I'm excited to express my interest in contributing to the GSSOC project and would like to request assignment of the issue titled "FAQ Section Sequencing"

Having reviewed the issue description, I'm confident in my ability to make a meaningful contribution towards resolving it. Could you please confirm if this issue is available for assignment?

I'm looking forward to the opportunity to contribute to the project

**Comment by Anushkabh** [comment]
@nandu-99 kindly provide the exact ss of the issue you want to solve

**Comment by nandu-99** [comment]
![Uploading Screenshot 2024-05-09 at 11.55.12 AM.png…]()

**Comment by nandu-99** [comment]
![Uploading Screenshot 2024-05-09 at 11.55.12 AM.png…]()

**Comment by nandu-99** [comment]
![Uploading Screenshot 2024-05-12 at 1.10.59 AM.png…]()

**Comment by nandu-99** [comment]
https://drive.google.com/file/d/14nF1CpigPiwFUZuGvNQb_qTwmQn0RgiO/view?usp=sharing

**Comment by MehekFatima** [comment]
I've just submitted a Pull Request for this issue. I would greatly appreciate it if you could take some time to review my Pull Request. @Anushkabh @nandu-99
