### ISSUE TITLE
DOC:

### ISSUE THREAD

**Issue by tmanas06** [Anushkabh/krishiconnect#83]
### What's wrong with the existing documentation

The current documentation lacks lots of information and is a lot plain , so i would like to update it by adding information like  Overview, features, contribution statement ,etc.

### Add ScreenShots

![image](https://github.com/Anushkabh/krishiconnect/assets/113188197/fc858f55-2d30-4036-b6af-fb6510d35d8e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anushkabh** [comment]
@tmanas06 kindly look the updated one and if you feel you can improve it then a raise a pr

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
