### ISSUE TITLE
Enhance MyCart UI and make it responsive.

### ISSUE THREAD

**Issue by AlaynaShaheen** [Anushkabh/krishiconnect#90]
### Describe the feature

The image in the hero section of MyCart page looks blur and is not clearly visible. Also the form "enter the details" can be made much better by improving UI. And the font on the image is also not clearly visible.

So we can change the style of background image and also the color and size of font present on image. Then the styles of enter details form can also be improved. And making it responsive

I am a contributor working under GSSoC'24. Please assign this issue to me.

### Add ScreenShots

Desktop view:
![Screenshot 2024-05-13 190323](https://github.com/Anushkabh/krishiconnect/assets/111679498/454b9f29-198a-42da-997c-449953d4fe06)
Mobile view:
![Screenshot 2024-05-13 190349](https://github.com/Anushkabh/krishiconnect/assets/111679498/ac1989cc-5c29-475f-9ddf-8cdd512ea0bc)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by AlaynaShaheen** [comment]
Thank you for assigning me @Anushkabh

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
