### ISSUE TITLE
Feat: good footer

### ISSUE THREAD

**Issue by 39palakved** [Anushkabh/krishiconnect#92]
### Describe the feature

I want to add a good responsive footer to this website 

### Add ScreenShots

![Screenshot_2024-05-13-21-24-13-02_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Anushkabh/krishiconnect/assets/99019333/55e86961-ca7f-434a-a758-6693a3f53343)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by RitiChandak** [comment]
@39palakved ??

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
