### ISSUE TITLE
Feat: Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Anushkabh/krishiconnect#95]
### Describe the feature

In your application anyone can use **temporary or disposable email**.
I will add a feature so that no one could use **temporary or disposable email**.
It will help to avoid any bot.
Assign me this work under GSSoC24, I will implement it.

### Add ScreenShots
![image](https://github.com/Anushkabh/krishiconnect/assets/73558583/84da06ba-7535-4935-8fdd-6177f8837fa7)

### Record

- [X] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by tushant-akar** [comment]
@Anushkabh Kindly assign me this issue.

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
