### ISSUE TITLE
Feat: testimonial section 

### ISSUE THREAD

**Issue by Anamika-Ratna** [Anushkabh/krishiconnect#96]
### Describe the feature

addition of testimonial section after "category" section

### Add ScreenShots

![Screenshot (668)](https://github.com/Anushkabh/krishiconnect/assets/122286548/46b5a1ef-188d-4d3e-ad0a-503b24681105)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by himanshu-03** [comment]
Hi there!

Thank you for opening this issue! 😊

I just wanted to check in and see if you need any help or guidance with this issue. If you have any questions or run into any challenges, please feel free to ask. I'm here to assist you!

Additionally, it's been some time since the issue was opened. If we don't hear back from you within a week, the issue will be closed or made available for someone else to work on.

Happy coding!
